spring:
  application:
    name: tasks-crud-aop
  profiles:
    include:
      - kafka
      - mail
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksappdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
